version: '3.8'

services:
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"  # Exposing default MongoDB port
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db 

  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5001:5000"  
    networks:
      - app_network
    volumes:
      - .:/backend

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"  
    volumes:
      - ./nginx:/etc/nginx  
      - ./nginx/html:/usr/share/nginx/html  
    depends_on:
      - backend
    networks:
      - app_network


volumes:
  mongodb_data:
    driver: local


networks:
  app_network:
    driver: bridge
